<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-10-06 18:48
=======
# Generated by Django 3.2.7 on 2021-10-11 04:20
>>>>>>> devIbe-merge

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
>>>>>>> devIbe-merge
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclamation', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notified', to='book.book')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> devIbe-merge
            ],
        ),
    ]
