# Generated by Django 3.2.7 on 2021-10-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='checked_out_books',
            field=models.ManyToManyField(blank=True, null=True, to='book.Book'),
        ),
    ]
