# Generated by Django 3.2.7 on 2021-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reserved_books',
            field=models.ManyToManyField(blank=True, related_name='reserved', to='book.Book'),
        ),
    ]
