# Generated by Django 3.2.7 on 2021-10-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_customuser_checked_out_books'),
        ('custom_user', '0002_customuser_reserved_books'),
    ]

    operations = [
    ]
