# Generated by Django 3.2.7 on 2021-10-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/profile.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
