# Generated by Django 3.2.7 on 2021-10-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
