# Generated by Django 3.2.7 on 2021-10-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.URLField(max_length=1500)),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('copies_available', models.PositiveIntegerField(default=2)),
                ('gutenberg_id', models.IntegerField(default=0)),
                ('is_reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
