# Generated by Django 3.2.7 on 2021-10-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_available',
        ),
        migrations.AddField(
            model_name='book',
            name='copies_available',
            field=models.IntegerField(default=2),
        ),
    ]
