# Generated by Django 3.2.7 on 2021-10-18 15:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
