# Generated by Django 3.2.7 on 2021-10-18 15:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_file',
            field=cloudinary.models.CloudinaryField(default='/static/images/placeholder.jpg', max_length=255),
        ),
    ]
