# Generated by Django 3.2.7 on 2021-10-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_file',
            field=models.ImageField(default='static/images/placeholder.jpg', upload_to='book_covers'),
        ),
    ]
